# Generated by Django 3.1.4 on 2021-01-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=30)),
                ('county', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_num', models.CharField(max_length=12)),
            ],
        ),
    ]
