# Generated by Django 3.1.4 on 2021-01-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210101_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
